project_name: trellis
before:
  hooks:
  - go mod download
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - 386
    - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - name: trellis-cli
    github:
      owner: roots
      name: homebrew-tap
    folder: Formula
    homepage:  https://roots.io/trellis
    description: A CLI to manage Trellis projects
    install: |
      bin.install "trellis"
    test: |
      system "#{bin}/trellis --autocomplete-install"
      system "#{bin}/trellis -v"
