version: 2.1

jobs:
  test:
    docker:
      - image: circleci/golang:1.12-buster
    steps:
      - run: go version
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go test -v ./...
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

workflows:
  test:
    jobs:
      - test
