version: 2.1

jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - run: go version
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go test -v ./...
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - run: go version
      - checkout
      - deploy: curl -sL https://git.io/goreleaser | bash

workflows:
  test:
    jobs:
      - test
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
